config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'cosmetics/search', to: 'cosmetics#search', as: :scan
  post 'cosmetics/search', to: 'cosmetics#create'

  get 'pages/user_profile' => 'pages#user_profile'

  # users can leave a review about a cosmetic and display them on cosmetic's page
  resources :cosmetics, except: [:destroy] do
    # The member scopes ensure that the id of the favourite is passed into the action,
    # while the method post ensures that the action will be sent securely to the db and not replicated on page refresh.
    # The generated route will look like this: cosmetics/:id/toggle_favorite
    member do
      post 'toggle_favorite', to: "cosmetics#toggle_favorite"
      get 'compare', to: 'cosmetics#compare'
      get 'confirm', to: 'cosmetics#confirm'
    end

    resources :reviews, only: %i[new create]
  end

  get 'pages/user_profile', to: 'pages#user_profile'
  # later on displaying ingredients info
  # resources :ingredients, only: [ :show ] ?? how to grab ingredients info ??
end

app/models/cosmetic.rb
class Cosmetic < ApplicationRecord
  has_many :reviews
  has_and_belongs_to_many :ingredients
  #validates :name, :description, :brand, :average_price, :category, presence: true
  acts_as_favoritable
  acts_as_taggable_on :tags
  acts_as_taggable_on :cosmetics
  has_one_attached :cosmetic_image
  TAGS = [ "Oil Free", "Purpicks", 'Silicone Free', "Water Free" ] + Ingredient.pluck(:name_en)
  INGREDIENTS = Ingredient.pluck(:name_en)
  scope :by_join_date, -> { order("created_at DESC") }
# other-tags ["For sensitive skin", "sulphate-free", "Canadian", "CertClean","Chemical Free", "Dairy Free", "EWG Verified", "EcoCert", "Fair Trade", "Gluten Free", "Hypoallergenic", "Natural", "No Talc", "Non-GMO", "Organic", "Peanut Free Product", "Sugar Free", "USDA Organic", "Vegan", "Alcohol Free", "Cruelty Free",]
  #the above is so we can search by tags
  include PgSearch::Model
  pg_search_scope :search_by_brand_and_description,
    against: [ :brand, :description ],
    using: {
      tsearch: { prefix: true }
    }

  def total_reviews
    total_reviews = self.reviews.count
    return total_reviews
  end

  def average_review
    if total_reviews == 0
      0
    else
    total_rating = self.reviews.sum(:rating)
    total_rating / total_reviews
    end
  end
end

app/controllers/cosmetics_controller.rb
class CosmeticsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  before_action :set_cosmetic, only: %i[show compare confirm update]
  before_action :skip_authorization, only: [:search, :compare]
  # The user must be logged in to like a cosmetic.
  # The toggle_favorite action is called if the user is logged in,
  # using the Devise helper.
  before_action :authenticate_user!, only: [:toggle_favorite, :update, :index]

  def create
    @cosmetic = Cosmetic.new({ cosmetic_image: cosmetic_params[:cosmetic_image], name: "Name", description: "Description", brand:
      "Brand", category: "Category" })
    cosmetic_policy_authorize
    if @cosmetic.save
      redirect_to confirm_cosmetic_path(@cosmetic)
    else
      redirect_to scan_path
    end
  end

  def new
    cosmetic_policy_authorize
    @cosmetic = Cosmetic.new
  end

  def index
    # @cosmetics = policy_scope(Cosmetic).first(50)
    @cosmetics = policy_scope(Cosmetic)
    # When we display all, we get some cosmetics with no brand, description, etc.
    # Display less so we don't get too much errors".
    # Later will implement search button anyway and will get only the ones we look for.

    # @favorite_cosmetics = current_user.favorited_by_type('Cosmetic')
    #manual typing search function below
    if params[:query].present?
      unformatted_search_terms = params[:query].split(",")
      formatted_search_terms = unformatted_search_terms.map { |term| term.squish }
      sql_query = " \
      cosmetics.brand @@ :query \
      OR cosmetics.name @@ :query \
      OR cosmetics.category @@ :query \
      OR tags.name @@ :query \
      "
      @cosmetics = []
      formatted_search_terms.each do |term|
        @cosmetics += Cosmetic.joins(:tags).where(sql_query, query: term).uniq
      end
      @cosmetics
    else
      @cosmetics = policy_scope(Cosmetic).first(50)
    end
  end
  #OR cosmetics.tags.tag_list[] @@ :query \

  def show
    cosmetic_policy_authorize
    @review = Review.new
  end

  def update
    @cosmetic.tag_list.add(cosmetic_params[:tag_list])
    @cosmetic.update(cosmetic_params)
    cosmetic_policy_authorize
    redirect_to cosmetic_path(@cosmetic)
  end

  def toggle_favorite
    # The toggle_favorite action finds the cosmetic to like through the id parameter.
    @cosmetic = Cosmetic.find_by(id: params[:id])
    cosmetic_policy_authorize
    # It checks if a user has liked it. If it’s been favourited before, it is now unfavorited and vice versa.
    current_user.favorited?(@cosmetic) ? current_user.unfavorite(@cosmetic) : current_user.favorite(@cosmetic)
  end

  def search
    if params[:cosmetic].present?
      #@cosmetic = Cosmetic.new(cosmetic_params)
      cosmetic_policy_authorize
      if @cosmetic.save
        redirect_to confirm_cosmetic_path(@cosmetic)
      else
        redirect_to root_path
      end
    end
  end

  def compare
    #@cosmetics = SearchJp.search
    @cosmetics = Cosmetic.includes(:ingredients).where.not(ingredients: {id: nil}).where(ingredients: {name_en: @cosmetic.tag_list })
    #@cosmetic_ingredients = Ingredient.find_by([:id]params[:cosmetic_id])
  end

  def confirm
    # Never comment when push on heroku
    if Rails.env == "development"
      image = "http://res.cloudinary.com/dhkk2emak/image/upload/v1/development/#{@cosmetic.cosmetic_image.key}"#helpers.url_for(@cosmetic.cosmetic_image)
    else
      image = "http://res.cloudinary.com/dhkk2emak/image/upload/v1/production/#{@cosmetic.cosmetic_image.key}"
    end
    @info = Ocr.extract_text(image)
    cosmetic_policy_authorize
  end

  private

  def cosmetic_policy_authorize
    authorize @cosmetic
  end

  def set_cosmetic
    @cosmetic = Cosmetic.find(params[:id])
  end

  def cosmetic_params
    params.require(:cosmetic).permit(:cosmetic_image, :name, :description, :brand, :average_price, :category, :ingredient_id, tag_list: [])
  end
end

app/views/cosmetics/_form_search.html.erb
<%= simple_form_for :search, url: scan_path, method: "patch" do |f| %>
  <%= f.input :cosmetic_image, as: :file, height: 200 %>
  <%= f.input :brand, input_html: {value: "EGO"} %>
  <%= f.input :name, input_html: {value: "#{@info[0].downcase.capitalize}"} %>
  <%= f.input :description, input_html: {value: "#{@info[1].downcase.capitalize} #{@info[2].downcase.capitalize}"} %>
  <%= f.submit "Search" %>
<% end %>

app/views/cosmetics/_ingredients_list.html.erb
  <div class="ingredient-body">
    <div data-controller="expandable">
      <div  class="row m-1" data-expandable-target="list" id="ingredient-id" >
        <% @cosmetic.ingredients.each do |ingredient| %>
          <li class="tag tag-green"><%= ingredient.name_en %></li>
        <% end %>
      </div>
      <% if @cosmetic.ingredients.size > 10 %>
        <button class="button w-100" data-action="click->expandable#expand">See all ingredients!</button>
      <% end %>
    </div>
  </div>
<%# <% if @cosmetic.tag_list.size > 0 %>
  <%# <div class="cosme-card-header-tags">
    <div class="row m-1"> %>
      <%# <% @cosmetic.tag_list.each do |tag| %>
        <%# <li class="tag tag-green"><%= tag</li> %>
      <%# <% end %>
      <%# <div class="cosme-card-line"><hr /></div>
    </div>
  </div> %>
<%# <% end %>

app/views/cosmetics/_mini_cosme_card.html.erb
<div class="mini-cosme-card">
  <div class="mini-cosme-card-header">
    <% if cosmetic.total_reviews > 0 %>
      <% if cosmetic.cosmetic_image.attached?%>
        <%= cl_image_tag cosmetic.cosmetic_image.key, class: "img" %>
      <%end %>

      <div class="mini-cosme-card-header-info">
        <div class="mini-cosme-card-header-info-rating">
          <h3 class="mini-cosme-card-header-info-rating-number"><%= cosmetic.average_review%></h3>
          <p class="mini-cosme-card-header-info-rating-text"><%= cosmetic.total_reviews %><br>ratings</p>
        </div>
        <p><%= render "components/average_star_rating",cosmetic: cosmetic%></p>
        <p class="mini-cosme-card-header-info-price"><span>¥<%= cosmetic.average_price %></span> avg.</p>
      </div>
    <% else %>
      <% if cosmetic.cosmetic_image.attached?%>
        <%= cl_image_tag cosmetic.cosmetic_image.key, class: "img rounded mx-auto d-block" %>
      <%end %>
    <% end %>
  </div>
  <div class="mini-cosme-card-line"><hr/></div>
  <div class="mini-cosme-card-body">
    <p class="mini-cosme-card-body-name"><%= cosmetic.name %></p>
    <p class="mini-cosme-card-body-brand"><%= cosmetic.brand.upcase %></p>
        <span class="row m-1">
        <% cosmetic.tag_list.each do |tag| %>
          <li class="mini-tag mini-tag-green"><%= tag %></li>
        <% end %>
        </span>
  </div>
  <div class="mini-cosme-card-body-bottom">
    <p class="mini-cosme-card-body-bottom-tag"><%= cosmetic.category.capitalize %></p>
    <%= link_to "See more", cosmetic_path(cosmetic), class: "button mini-cosme-card-body-bottom-button"  %>
  </div>
</div>

app/views/cosmetics/_mini_cosme_card_with_favorite.html.erb
<div class="favorite" data-id="<%= cosmetic.id %>">
  <div class="mini-cosme-card">
    <div class="mini-cosme-card-header">
      <% if cosmetic.cosmetic_image.attached?%>
        <%= cl_image_tag cosmetic.cosmetic_image.key, class: "img"%>
      <%end %>
      <div class="mini-cosme-card-header-info">
        <div class="favorite-icon">
          <%= link_to toggle_favorite_cosmetic_path(cosmetic), remote: true, method: :post do %>
            <%= render 'cosmetics/like_button', cosmetic: cosmetic %>
          <% end %>
        </div>
        <div class="mini-cosme-card-header-info-rating">
          <h3 class="mini-cosme-card-header-info-rating-number"><%= cosmetic.average_review %></h3>
          <p class="mini-cosme-card-header-info-rating-text"><%= cosmetic.total_reviews %><br>ratings</p>
        </div>
        <p><%= render "components/average_star_rating",cosmetic: cosmetic%></p>
        <p class="mini-cosme-card-header-info-price"><span>¥<%= cosmetic.average_price %></span> avg.</p>
          <span class="row m-1">
          <% cosmetic.tag_list.each do |tag| %>
            <li class="mini-tag mini-tag-green"><%= tag %></li>
          <% end %>
          </span>
      </div>
    </div>
    <div class="mini-cosme-card-line"><hr /></div>
    <div class="mini-cosme-card-body">
      <p class="mini-cosme-card-body-name"><%= cosmetic.name %></p>
      <p class="mini-cosme-card-body-brand"><%= cosmetic.brand.upcase %></p>
    </div>
      <div class="mini-cosme-card-body-bottom">
        <p class="mini-cosme-card-body-bottom-tag"><%= cosmetic.category.capitalize %></p>
        <%= link_to "See more", cosmetic_path(cosmetic), class: "button mini-cosme-card-body-bottom-button"  %>
      </div>
  </div>
</div>

app/views/cosmetics/_mini_cosme_compare.html.erb
<div class="favorite" data-id="<%= cosmetic.id %>">
  <div class="mini-cosme-card">
    <div class="mini-cosme-card-header">
      <% if cosmetic.cosmetic_image.attached?%>
        <%= cl_image_tag cosmetic.cosmetic_image.key, class: "img"%>
      <%end %>

      <div class="mini-cosme-card-header-info">

        <div class="favorite-icon">
          <%= link_to toggle_favorite_cosmetic_path(cosmetic), remote: true, method: :post do %>
            <%= render 'cosmetics/like_button', cosmetic: cosmetic %>
          <% end %>
        </div>

        <div class="mini-cosme-card-header-info-rating">
          <h3 class="mini-cosme-card-header-info-rating-number"><%= cosmetic.average_review %></h3>
          <p class="mini-cosme-card-header-info-rating-text"><%= cosmetic.total_reviews %><br>ratings</p>
        </div>
        <p><%= render "components/average_star_rating",cosmetic: cosmetic%></p>

        <p class="mini-cosme-card-header-info-price"><span>¥<%= cosmetic.average_price %></span> avg.</p>

        <span class="row m-1">
        <% cosmetic.tag_list.each do |tag| %>
          <li class="mini-tag mini-tag-green"><%= tag %></li>
        <% end %>
        </span>

      </div>
    </div>
    <div class="mini-cosme-card-line"><hr /></div>

    <div class="mini-cosme-card-body">
      <p class="mini-cosme-card-body-name"><%= cosmetic.name %></p>
      <p class="mini-cosme-card-body-brand"><%= cosmetic.brand.upcase %></p>

      <%# INGREDIENTS %>
      <span class="row m-1">
        <% cosmetic.ingredients.each do |ingredient| %>
          <li class="mini-tag mini-tag-green"><%= ingredient.name_en %></li>
        <% end %>
      </span>

    </div>

      <div class="mini-cosme-card-body-bottom">
        <p class="mini-cosme-card-body-bottom-tag"><%= cosmetic.category.capitalize %></p>

        <%= link_to "See more", cosmetic_path(cosmetic), class: "button mini-cosme-card-body-bottom-button"  %>
      </div>
  </div>
</div>

app/views/cosmetics/_review_card.html.erb
<div class=“review-card” style="height: 100%; padding-top: 1rem;">
  <div class=“review-card-body”>
    <div class="d-flex">
      <h5 class="card-title mr-2"><strong><%= review.user.name %></strong></h5>
        <p class= "card-subtitle mb01 text-muted">
          <span class=“text-muted”><%= render "components/star_rating", review: review %></span>
        </p>
    </div>
      <div class="review-card-body">
        <p class="p-review-card-content"><%= review.content %></p>
      </div>
        <div class="mt-2">
          <a class="h5-shop-url"> <%= review.shop_url %></a>
        </div>
  </div>
</div>

app/views/cosmetics/_review_card_list.html.erb
<% if @cosmetic.reviews.count >= 3 %>
<div  data-controller="expandable">
    <div data-expandable-target="list" id="review">
          <% reviews.each do |review| %>
          <%= render "review_card", review: review %>
        <% end %>
    </div>
    <button class="button w-100" data-action="click->expandable#expand">See All Reviews!</button>
  </div>
<% end %>

app/views/cosmetics/_review_form.html.erb
<button type="button" class="button button-leave-review" data data-toggle="modal" data-backdrop="false" data-target=".bd-review-form-modal-sm" data-controller="review_reset" data-collapsible-target="reset">Leave a review!</button>
                                                                                                                                                <%# You need to set the data controller to connect to stimulus and then the target in order to define your static target %>
<div class="modal bd-review-form-modal-sm" id="reviewModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" data-controller="collapsible" data-collapsible-target="hidden"> <%# You need to put the controller in a place where it can encase everthing you want to target %>
  <div class="modal-dialog modal-sm mt-10">
    <div class="modal-content">
      <div class= "Review-form-card">
        <div class= "row d-flex justify-content-center mt-2">
          <%= simple_form_for([ @cosmetic, @review ], remote: true, data: {action: "submit->collapsible#collapse"}) do |f| %>
            <%= f.input :rating, collection: (1..5).to_a, label: "Rate Your Product!!!" %>
            <%= f.input :shop_url %>
            <%= f.input :content, as: :text, label: false %>
            <div class="modal-footer">
              <button type="button" class="button c1" data-dismiss="modal">Close</button>
              <%= f.submit "Leave Review", class: 'button', data: {action: "click->collapsible#collapse"}%>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cosmetics/compare.html.erb
<header class="container-fluid col-12">
  <h1 class="text-center">Your product</h1>
  <%= render 'cosmetics/mini_cosme_card', cosmetic: @cosmetic %>
</header>

<div class="row global-padding">
  <div class="col-xs-12 col-sm-6">
    <h3 class="text-center m-2">Pick your Japanese product</h3>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <% @cosmetics.each do |cosmetic| %>
            <%= render 'cosmetics/mini_cosme_compare', cosmetic: cosmetic %>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/cosmetics/confirm.html.erb
<div class="container">
  <div class="row justify-content-center text-center confirm-page">
    <div class="col-10">
      <h2 class="my-4" >Add ingredients to your product and check the informations</h2>
        <tr>
            <td><%= cl_image_tag @cosmetic.cosmetic_image.key , alt: "alttext", style: "width: 300px", class:"confirm-page-picture" %></td>
        </tr>
        <h4>Choose from the list below or add your own:</h4>
        <% if policy(Cosmetic).update? %>
          <%= simple_form_for(@cosmetic) do |f| %>
            <%= f.input :tag_list,
                        collection: Cosmetic::INGREDIENTS,
                        label: 'Add ingredients ',
                        input_html: {multiple: true, :maxlength =>200,:style=> 'width: 100%',
                        data: { controller: "select2", select2_options_value: {tags: true} }},
                        class: "p-1 tag-form" %>
            <%= f.input :brand, input_html: {value: "#{@info[0].downcase.capitalize}"} %>
            <%= f.input :name, input_html: {value: "#{@info[1].downcase.capitalize}"} %>
            <% if @info[5].present? %>
              <%= f.input :description, input_html: {value: "#{@info[2].downcase.capitalize}, #{@info[3].downcase.capitalize}, #{@info[4].downcase.capitalize}, #{@info[5].downcase.capitalize} "} %>
            <% elsif @info[4].present? %>
              <%= f.input :description, input_html: {value: "#{@info[2].downcase.capitalize}, #{@info[3].downcase.capitalize}, #{@info[4].downcase.capitalize}" } %>
            <% else %>
              <%= f.input :description, input_html: {value: "#{@info[2].downcase.capitalize}, #{@info[3].downcase.capitalize}" } %>
            <% end %>
            <%= f.input :category, collection: ["skincare", "lipcare", "eyecare"] %>
            <p>Where did you buy your product?</p>
            <%= f.country_select :country_of_origin,
                                  {priority_countries: ["JP", "UK", "US", "FR"]},
                                  {class: "form-control"},
                                  as: :country %>
            <%= f.submit "Add Tags", class: "button tag-form-button" %>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/cosmetics/index.html.erb
<div class="row global-padding">
  <div class="col-xs-12 col-sm-6">
    <%# <div class="mini-cosme-card"> %>
      <div class="form-inline d-flex justify-content-center col-12"><%= render "shared/search_form" %></div>
    <%# </div> %>
    <h3 class="text-center m-2">First <%= @cosmetics.count %> cosmetics out of <%= Cosmetic.all.count %></h3>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <% @cosmetics.each do |cosmetic| %>
            <%= render 'cosmetics/mini_cosme_card_with_favorite', cosmetic: cosmetic %>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/cosmetics/search.html.erb
<div class="container" data-controller="processing" data-processing-target="processingPage">
  <div data-processing-target="spinner" class="processing-modal d-none">
    <h1 class="justify-text-center">Scanning</h1>
  </div>
  <div class="row justify-content-center text-center">
    <div class="col-12">
      <div class="search-card">
        <div class="search-card-body">
          <h3 class="my-2" >Take or Upload <br> a picture of your product</h3>
          <p>Make sure that the text is visible</p>
          <div class="form-inputs mt-4">
            <%= simple_form_for Cosmetic.new , url: cosmetics_path, method: "post", class: "row justify-content-center" do |f| %>
              <%= f.input :cosmetic_image, label: false, as: :file %>
              <%= f.submit "Scan your product", class: "button cosme-card-body-button-match", data: {action: "click->processing#loadingCosme"} %>
            <% end %>
          </div>
          <div class="cosme-card-line"><hr /></div>
          <h3 class="mb-4" >Or search directly<br> for your product</h3>
          <div class="form-inline d-flex justify-content-center col-12"><%= render "shared/search_form" %></div>
        </div>
    </div>
  </div>
</div>

app/views/cosmetics/show.html.erb
<div class="col-12 col-md-4 global-padding" data-controller="processing" data-processing-target="processingPage">
  <div data-processing-target="spinner" class="processing-modal d-none">
    <h1 class="justify-text-center">Translating</h1>
  </div>

  <div class="cosme-card">
  <%# HEADER = PICTURE %>
  <div class="cosme-card-image">
    <%= cl_image_tag @cosmetic.cosmetic_image.key, class: "img"%>
  </div>

  <%# HEADER = PRICE + REVIEWS %>
  <div class="cosme-card-header">
    <% if @cosmetic.total_reviews > 0 %>
      <div class="cosme-card-header-info">
        <div class="cosme-card-header-info-rating">
          <div class="cosme-card-header-info-rating-numbers">
            <h3 class="cosme-card-header-info-rating-number"><%= @cosmetic.average_review%></h3>
            <p class="cosme-card-header-info-rating-text"><%= @cosmetic.total_reviews %><br>ratings</p>
          </div>
          <p class="mb-0"><%= render "components/average_star_rating", cosmetic: @cosmetic%></p>
        </div>
        <p class="cosme-card-header-info-price"><span>¥<%= @cosmetic.average_price %></span> avg.</p>
      </div>
      <div class="cosme-card-line"><hr /></div>
    <% end %>
  </div>

  <div class="cosme-card-body">
    <%# FAVORITES %>
    <div class="favorite-icon">
      <%= link_to toggle_favorite_cosmetic_path(@cosmetic), remote: true, method: :post do %>
        <%= render 'cosmetics/like_button', cosmetic: @cosmetic %>
      <% end %>
    </div>

    <h3> <%= @cosmetic.name %></h3>
      <p class="cosme-card-body-brand"><%= @cosmetic.brand.upcase %></p>
      <div class="tag tag-brown"><%= @cosmetic.category.capitalize %></div>
    <div class="cosme-card-line"><hr /></div>

    <%# DESCRIPTION %>
      <p><%= @cosmetic.description %></p>
        <%# <div class="cosme-card-line"><hr /></div> %>

    <%# INGREDIENTS LIST %>
    <% if @cosmetic.ingredients.exists? %>
      <div class="cosme-card-header-tags">
        <%= render 'cosmetics/ingredients_list', locals: {cosmetic: @cosmetic, ingredient: @ingredient} %>
      </div>
    <% end %>
          <%# <div class="cosme-card-line"><hr /></div> %>
    <% if policy(Cosmetic).update? %>
      <%= render 'layouts/tag_form' %>
    <% end %>
    <div class="cosme-card-line"><hr /></div>

    <% if @cosmetic.tag_list.size > 0 %>
      <div class="cosme-card-header-tags">
        <div class="row m-1">
          <% @cosmetic.tag_list.each do |tag| %>
            <li class="tag tag-green"><%= tag %></li>
          <% end %>
        </div>
      </div>
      <div class="cosme-card-line"><hr /></div>
    <% end %>

    <% if @cosmetic.ingredients.blank? %>
      <p>Compare your product and find the best fit through the tags</p>
      <%= link_to "Find my match", compare_cosmetic_path(@cosmetic), class: "button cosme-card-body-button-match", data: {action: "click->processing#loading"} %>
      <div class="cosme-card-line"><hr /></div>
    <% end %>

    <%# REVIEWS %>
    <div class="review-all"> <%= render "cosmetics/review_form", locals: {cosmetic: @cosmetic, review: @review} %> </div>
    <div class="user-reviews"> <%= render "review_card_list", reviews: @cosmetic.reviews.reverse %> </div>
  </div>
</div>

app/views/cosmetics/toggle_favorite.js.erb
var cosmeticId = '<%= @cosmetic.id %>'

function toggleLikeButton(cosmeticId, favoritedCosmetic) {
  let likeButton = document.querySelector(`.like-icon[data-id='${cosmeticId}']`)
  likeButton.classList.toggle('red');
  if (likeButton.classList.contains('red')) {
    const favoriteList = document.querySelector('.favorites');
    favoriteList.insertAdjacentHTML('beforeend', favoritedCosmetic)
  }
  else {
    document.querySelector(`.favorite[data-id='${cosmeticId}']`).remove()
  }
}

toggleLikeButton(cosmeticId, '<%= j render "cosmetics/mini_cosme_card_with_favorite", cosmetic: @cosmetic %>');